# Generated by Django 2.2.5 on 2019-09-09 20:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_statement', models.TextField(max_length=500, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('cover_letter', models.FileField(null=True, upload_to='')),
                ('github', models.URLField(null=True, validators=[django.core.validators.URLValidator])),
                ('linkedin', models.URLField(null=True, validators=[django.core.validators.URLValidator])),
                ('portfolio', models.URLField(null=True, validators=[django.core.validators.URLValidator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_orgs', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(500)])),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('submittal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_resume', to='CareerFlash.Submittal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Cover_Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(500)])),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('submittal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_coverletter', to='CareerFlash.Submittal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_coverletter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('contact_name', models.CharField(max_length=255, null=True)),
                ('contact_email', models.CharField(max_length=255, null=True)),
                ('contact_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
