# Generated by Django 2.2.5 on 2019-09-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0002_auto_20190913_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='owner',
        ),
    ]
