# Generated by Django 2.2.5 on 2019-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0004_auto_20190916_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='frontend/public/tempdocs/pictures'),
        ),
    ]
