# Generated by Django 2.2.5 on 2019-09-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0004_auto_20190916_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
