# Generated by Django 2.2.5 on 2019-09-16 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0005_auto_20190916_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
