# Generated by Django 2.2.5 on 2019-09-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0005_profile_profile_picture'),
        ('CareerFlash', '0006_auto_20190916_1843'),
    ]

    operations = [
    ]
