# Generated by Django 2.2.5 on 2019-09-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0007_merge_20190916_2149'),
        ('CareerFlash', '0008_auto_20190916_2018'),
    ]

    operations = [
    ]
