# Generated by Django 2.2.5 on 2019-09-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0010_auto_20190917_1550'),
        ('CareerFlash', '0009_merge_20190917_1452'),
    ]

    operations = [
    ]
