# Generated by Django 2.2.5 on 2019-09-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0013_auto_20190918_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orginization',
            old_name='owner_username',
            new_name='owner',
        ),
    ]
