# Generated by Django 2.2.5 on 2019-09-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0011_merge_20190917_1601'),
        ('CareerFlash', '0014_auto_20190918_0310'),
    ]

    operations = [
    ]
