# Generated by Django 2.2.5 on 2019-09-18 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0014_auto_20190918_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
