# Generated by Django 2.2.5 on 2019-09-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0015_merge_20190918_1845'),
        ('CareerFlash', '0015_profile_profile_picture'),
    ]

    operations = [
    ]
