# Generated by Django 2.2.5 on 2019-09-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0015_merge_20190918_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='frontend/public/tempdocs/coverletter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='frontend/public/tempdocs/resume'),
        ),
    ]
