# Generated by Django 2.2.5 on 2019-09-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0016_merge_20190918_1930'),
        ('CareerFlash', '0016_merge_20190918_1913'),
    ]

    operations = [
    ]
