# Generated by Django 2.2.5 on 2019-09-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0015_profile_profile_picture'),
        ('CareerFlash', '0016_auto_20190918_1926'),
    ]

    operations = [
    ]
