# Generated by Django 2.2.5 on 2019-09-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0017_merge_20190918_2020'),
        ('CareerFlash', '0017_merge_20190918_1944'),
    ]

    operations = [
    ]
