# Generated by Django 2.2.5 on 2019-09-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlash', '0018_merge_20190918_2113'),
        ('CareerFlash', '0018_merge_20190918_2315'),
    ]

    operations = [
    ]
